// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * @file MessageHeader.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "protocols/dds/MessageHeader.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


eprosima::rpc::protocol::EntityId_t::EntityId_t()
{
    // m_entityKey com.eprosima.idl.parser.typecode.ArrayTypeCode@3c19aaa5
    memset(&m_entityKey, 0, (3) * 1);
    // m_entityKind com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3349e9bb
    m_entityKind = 0;

}

eprosima::rpc::protocol::EntityId_t::~EntityId_t()
{


}

eprosima::rpc::protocol::EntityId_t::EntityId_t(
        const EntityId_t& x)
{
    m_entityKey = x.m_entityKey;
    m_entityKind = x.m_entityKind;
}

eprosima::rpc::protocol::EntityId_t::EntityId_t(
        EntityId_t&& x)
{
    m_entityKey = std::move(x.m_entityKey);
    m_entityKind = x.m_entityKind;
}

eprosima::rpc::protocol::EntityId_t& eprosima::rpc::protocol::EntityId_t::operator =(
        const EntityId_t& x)
{

    m_entityKey = x.m_entityKey;
    m_entityKind = x.m_entityKind;

    return *this;
}

eprosima::rpc::protocol::EntityId_t& eprosima::rpc::protocol::EntityId_t::operator =(
        EntityId_t&& x)
{

    m_entityKey = std::move(x.m_entityKey);
    m_entityKind = x.m_entityKind;

    return *this;
}

bool eprosima::rpc::protocol::EntityId_t::operator ==(
        const EntityId_t& x) const
{

    return (m_entityKey == x.m_entityKey && m_entityKind == x.m_entityKind);
}

bool eprosima::rpc::protocol::EntityId_t::operator !=(
        const EntityId_t& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::EntityId_t::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ((3) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::EntityId_t::getCdrSerializedSize(
        const eprosima::rpc::protocol::EntityId_t& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    if ((3) > 0)
    {
        current_alignment += ((3) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::EntityId_t::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_entityKey;

    scdr << m_entityKind;

}

void eprosima::rpc::protocol::EntityId_t::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_entityKey;

    dcdr >> m_entityKind;
}

/*
 * @brief This function copies the value in member entityKey
 * @param _entityKey New value to be copied in member entityKey
 */
void eprosima::rpc::protocol::EntityId_t::entityKey(
        const std::array<uint8_t, 3>& _entityKey)
{
    m_entityKey = _entityKey;
}

/*
 * @brief This function moves the value in member entityKey
 * @param _entityKey New value to be moved in member entityKey
 */
void eprosima::rpc::protocol::EntityId_t::entityKey(
        std::array<uint8_t, 3>&& _entityKey)
{
    m_entityKey = std::move(_entityKey);
}

/*
 * @brief This function returns a constant reference to member entityKey
 * @return Constant reference to member entityKey
 */
const std::array<uint8_t, 3>& eprosima::rpc::protocol::EntityId_t::entityKey() const
{
    return m_entityKey;
}

/*
 * @brief This function returns a reference to member entityKey
 * @return Reference to member entityKey
 */
std::array<uint8_t, 3>& eprosima::rpc::protocol::EntityId_t::entityKey()
{
    return m_entityKey;
}
/*
 * @brief This function sets a value in member entityKind
 * @param _entityKind New value for member entityKind
 */
void eprosima::rpc::protocol::EntityId_t::entityKind(
        uint8_t _entityKind)
{
    m_entityKind = _entityKind;
}

/*
 * @brief This function returns the value of member entityKind
 * @return Value of member entityKind
 */
uint8_t eprosima::rpc::protocol::EntityId_t::entityKind() const
{
    return m_entityKind;
}

/*
 * @brief This function returns a reference to member entityKind
 * @return Reference to member entityKind
 */
uint8_t& eprosima::rpc::protocol::EntityId_t::entityKind()
{
    return m_entityKind;
}


size_t eprosima::rpc::protocol::EntityId_t::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool eprosima::rpc::protocol::EntityId_t::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::EntityId_t::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

eprosima::rpc::protocol::GUID_t::GUID_t()
{
    // m_guidPrefix com.eprosima.idl.parser.typecode.AliasTypeCode@2a3b5b47
    memset(&m_guidPrefix, 0, (12) * 1);
    // m_entityId com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@689604d9


}

eprosima::rpc::protocol::GUID_t::~GUID_t()
{


}

eprosima::rpc::protocol::GUID_t::GUID_t(
        const GUID_t& x)
{
    m_guidPrefix = x.m_guidPrefix;
    m_entityId = x.m_entityId;
}

eprosima::rpc::protocol::GUID_t::GUID_t(
        GUID_t&& x)
{
    m_guidPrefix = std::move(x.m_guidPrefix);
    m_entityId = std::move(x.m_entityId);
}

eprosima::rpc::protocol::GUID_t& eprosima::rpc::protocol::GUID_t::operator =(
        const GUID_t& x)
{

    m_guidPrefix = x.m_guidPrefix;
    m_entityId = x.m_entityId;

    return *this;
}

eprosima::rpc::protocol::GUID_t& eprosima::rpc::protocol::GUID_t::operator =(
        GUID_t&& x)
{

    m_guidPrefix = std::move(x.m_guidPrefix);
    m_entityId = std::move(x.m_entityId);

    return *this;
}

bool eprosima::rpc::protocol::GUID_t::operator ==(
        const GUID_t& x) const
{

    return (m_guidPrefix == x.m_guidPrefix && m_entityId == x.m_entityId);
}

bool eprosima::rpc::protocol::GUID_t::operator !=(
        const GUID_t& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::GUID_t::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ((12) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += eprosima::rpc::protocol::EntityId_t::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::GUID_t::getCdrSerializedSize(
        const eprosima::rpc::protocol::GUID_t& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    if ((12) > 0)
    {
        current_alignment += ((12) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }

    current_alignment += eprosima::rpc::protocol::EntityId_t::getCdrSerializedSize(data.entityId(), current_alignment);

    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::GUID_t::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_guidPrefix;

    scdr << m_entityId;

}

void eprosima::rpc::protocol::GUID_t::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_guidPrefix;

    dcdr >> m_entityId;
}

/*
 * @brief This function copies the value in member guidPrefix
 * @param _guidPrefix New value to be copied in member guidPrefix
 */
void eprosima::rpc::protocol::GUID_t::guidPrefix(
        const eprosima::rpc::protocol::GuidPrefix_t& _guidPrefix)
{
    m_guidPrefix = _guidPrefix;
}

/*
 * @brief This function moves the value in member guidPrefix
 * @param _guidPrefix New value to be moved in member guidPrefix
 */
void eprosima::rpc::protocol::GUID_t::guidPrefix(
        eprosima::rpc::protocol::GuidPrefix_t&& _guidPrefix)
{
    m_guidPrefix = std::move(_guidPrefix);
}

/*
 * @brief This function returns a constant reference to member guidPrefix
 * @return Constant reference to member guidPrefix
 */
const eprosima::rpc::protocol::GuidPrefix_t& eprosima::rpc::protocol::GUID_t::guidPrefix() const
{
    return m_guidPrefix;
}

/*
 * @brief This function returns a reference to member guidPrefix
 * @return Reference to member guidPrefix
 */
eprosima::rpc::protocol::GuidPrefix_t& eprosima::rpc::protocol::GUID_t::guidPrefix()
{
    return m_guidPrefix;
}
/*
 * @brief This function copies the value in member entityId
 * @param _entityId New value to be copied in member entityId
 */
void eprosima::rpc::protocol::GUID_t::entityId(
        const eprosima::rpc::protocol::EntityId_t& _entityId)
{
    m_entityId = _entityId;
}

/*
 * @brief This function moves the value in member entityId
 * @param _entityId New value to be moved in member entityId
 */
void eprosima::rpc::protocol::GUID_t::entityId(
        eprosima::rpc::protocol::EntityId_t&& _entityId)
{
    m_entityId = std::move(_entityId);
}

/*
 * @brief This function returns a constant reference to member entityId
 * @return Constant reference to member entityId
 */
const eprosima::rpc::protocol::EntityId_t& eprosima::rpc::protocol::GUID_t::entityId() const
{
    return m_entityId;
}

/*
 * @brief This function returns a reference to member entityId
 * @return Reference to member entityId
 */
eprosima::rpc::protocol::EntityId_t& eprosima::rpc::protocol::GUID_t::entityId()
{
    return m_entityId;
}

size_t eprosima::rpc::protocol::GUID_t::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool eprosima::rpc::protocol::GUID_t::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::GUID_t::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

eprosima::rpc::protocol::SequenceNumber_t::SequenceNumber_t()
{
    // m_high com.eprosima.idl.parser.typecode.PrimitiveTypeCode@18078bef
    m_high = 0;
    // m_low com.eprosima.idl.parser.typecode.PrimitiveTypeCode@145f66e3
    m_low = 0;

}

eprosima::rpc::protocol::SequenceNumber_t::~SequenceNumber_t()
{


}

eprosima::rpc::protocol::SequenceNumber_t::SequenceNumber_t(
        const SequenceNumber_t& x)
{
    m_high = x.m_high;
    m_low = x.m_low;
}

eprosima::rpc::protocol::SequenceNumber_t::SequenceNumber_t(
        SequenceNumber_t&& x)
{
    m_high = x.m_high;
    m_low = x.m_low;
}

eprosima::rpc::protocol::SequenceNumber_t& eprosima::rpc::protocol::SequenceNumber_t::operator =(
        const SequenceNumber_t& x)
{

    m_high = x.m_high;
    m_low = x.m_low;

    return *this;
}

eprosima::rpc::protocol::SequenceNumber_t& eprosima::rpc::protocol::SequenceNumber_t::operator =(
        SequenceNumber_t&& x)
{

    m_high = x.m_high;
    m_low = x.m_low;

    return *this;
}

bool eprosima::rpc::protocol::SequenceNumber_t::operator ==(
        const SequenceNumber_t& x) const
{

    return (m_high == x.m_high && m_low == x.m_low);
}

bool eprosima::rpc::protocol::SequenceNumber_t::operator !=(
        const SequenceNumber_t& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::SequenceNumber_t::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::SequenceNumber_t::getCdrSerializedSize(
        const eprosima::rpc::protocol::SequenceNumber_t& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::SequenceNumber_t::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_high;
    scdr << m_low;

}

void eprosima::rpc::protocol::SequenceNumber_t::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_high;
    dcdr >> m_low;
}

/*
 * @brief This function sets a value in member high
 * @param _high New value for member high
 */
void eprosima::rpc::protocol::SequenceNumber_t::high(
        int32_t _high)
{
    m_high = _high;
}

/*
 * @brief This function returns the value of member high
 * @return Value of member high
 */
int32_t eprosima::rpc::protocol::SequenceNumber_t::high() const
{
    return m_high;
}

/*
 * @brief This function returns a reference to member high
 * @return Reference to member high
 */
int32_t& eprosima::rpc::protocol::SequenceNumber_t::high()
{
    return m_high;
}

/*
 * @brief This function sets a value in member low
 * @param _low New value for member low
 */
void eprosima::rpc::protocol::SequenceNumber_t::low(
        uint32_t _low)
{
    m_low = _low;
}

/*
 * @brief This function returns the value of member low
 * @return Value of member low
 */
uint32_t eprosima::rpc::protocol::SequenceNumber_t::low() const
{
    return m_low;
}

/*
 * @brief This function returns a reference to member low
 * @return Reference to member low
 */
uint32_t& eprosima::rpc::protocol::SequenceNumber_t::low()
{
    return m_low;
}


size_t eprosima::rpc::protocol::SequenceNumber_t::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool eprosima::rpc::protocol::SequenceNumber_t::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::SequenceNumber_t::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

eprosima::rpc::protocol::SampleIdentity_t::SampleIdentity_t()
{
    // m_writer_guid com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@3023df74

    // m_sequence_number com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@313ac989


}

eprosima::rpc::protocol::SampleIdentity_t::~SampleIdentity_t()
{


}

eprosima::rpc::protocol::SampleIdentity_t::SampleIdentity_t(
        const SampleIdentity_t& x)
{
    m_writer_guid = x.m_writer_guid;
    m_sequence_number = x.m_sequence_number;
}

eprosima::rpc::protocol::SampleIdentity_t::SampleIdentity_t(
        SampleIdentity_t&& x)
{
    m_writer_guid = std::move(x.m_writer_guid);
    m_sequence_number = std::move(x.m_sequence_number);
}

eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::SampleIdentity_t::operator =(
        const SampleIdentity_t& x)
{

    m_writer_guid = x.m_writer_guid;
    m_sequence_number = x.m_sequence_number;

    return *this;
}

eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::SampleIdentity_t::operator =(
        SampleIdentity_t&& x)
{

    m_writer_guid = std::move(x.m_writer_guid);
    m_sequence_number = std::move(x.m_sequence_number);

    return *this;
}

bool eprosima::rpc::protocol::SampleIdentity_t::operator ==(
        const SampleIdentity_t& x) const
{

    return (m_writer_guid == x.m_writer_guid && m_sequence_number == x.m_sequence_number);
}

bool eprosima::rpc::protocol::SampleIdentity_t::operator !=(
        const SampleIdentity_t& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::SampleIdentity_t::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::GUID_t::getMaxCdrSerializedSize(current_alignment);
    current_alignment += eprosima::rpc::protocol::SequenceNumber_t::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::SampleIdentity_t::getCdrSerializedSize(
        const eprosima::rpc::protocol::SampleIdentity_t& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::GUID_t::getCdrSerializedSize(data.writer_guid(), current_alignment);
    current_alignment += eprosima::rpc::protocol::SequenceNumber_t::getCdrSerializedSize(data.sequence_number(), current_alignment);

    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::SampleIdentity_t::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_writer_guid;
    scdr << m_sequence_number;

}

void eprosima::rpc::protocol::SampleIdentity_t::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_writer_guid;
    dcdr >> m_sequence_number;
}

/*
 * @brief This function copies the value in member writer_guid
 * @param _writer_guid New value to be copied in member writer_guid
 */
void eprosima::rpc::protocol::SampleIdentity_t::writer_guid(
        const eprosima::rpc::protocol::GUID_t& _writer_guid)
{
    m_writer_guid = _writer_guid;
}

/*
 * @brief This function moves the value in member writer_guid
 * @param _writer_guid New value to be moved in member writer_guid
 */
void eprosima::rpc::protocol::SampleIdentity_t::writer_guid(
        eprosima::rpc::protocol::GUID_t&& _writer_guid)
{
    m_writer_guid = std::move(_writer_guid);
}

/*
 * @brief This function returns a constant reference to member writer_guid
 * @return Constant reference to member writer_guid
 */
const eprosima::rpc::protocol::GUID_t& eprosima::rpc::protocol::SampleIdentity_t::writer_guid() const
{
    return m_writer_guid;
}

/*
 * @brief This function returns a reference to member writer_guid
 * @return Reference to member writer_guid
 */
eprosima::rpc::protocol::GUID_t& eprosima::rpc::protocol::SampleIdentity_t::writer_guid()
{
    return m_writer_guid;
}
/*
 * @brief This function copies the value in member sequence_number
 * @param _sequence_number New value to be copied in member sequence_number
 */
void eprosima::rpc::protocol::SampleIdentity_t::sequence_number(
        const eprosima::rpc::protocol::SequenceNumber_t& _sequence_number)
{
    m_sequence_number = _sequence_number;
}

/*
 * @brief This function moves the value in member sequence_number
 * @param _sequence_number New value to be moved in member sequence_number
 */
void eprosima::rpc::protocol::SampleIdentity_t::sequence_number(
        eprosima::rpc::protocol::SequenceNumber_t&& _sequence_number)
{
    m_sequence_number = std::move(_sequence_number);
}

/*
 * @brief This function returns a constant reference to member sequence_number
 * @return Constant reference to member sequence_number
 */
const eprosima::rpc::protocol::SequenceNumber_t& eprosima::rpc::protocol::SampleIdentity_t::sequence_number() const
{
    return m_sequence_number;
}

/*
 * @brief This function returns a reference to member sequence_number
 * @return Reference to member sequence_number
 */
eprosima::rpc::protocol::SequenceNumber_t& eprosima::rpc::protocol::SampleIdentity_t::sequence_number()
{
    return m_sequence_number;
}

size_t eprosima::rpc::protocol::SampleIdentity_t::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool eprosima::rpc::protocol::SampleIdentity_t::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::SampleIdentity_t::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}






eprosima::rpc::protocol::RequestHeader::RequestHeader()
{
    // m_requestId com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@31304f14

    // m_instanceName com.eprosima.idl.parser.typecode.AliasTypeCode@34a3d150
    m_instanceName ="";

}

eprosima::rpc::protocol::RequestHeader::~RequestHeader()
{


}

eprosima::rpc::protocol::RequestHeader::RequestHeader(
        const RequestHeader& x)
{
    m_requestId = x.m_requestId;
    m_instanceName = x.m_instanceName;
}

eprosima::rpc::protocol::RequestHeader::RequestHeader(
        RequestHeader&& x)
{
    m_requestId = std::move(x.m_requestId);
    m_instanceName = std::move(x.m_instanceName);
}

eprosima::rpc::protocol::RequestHeader& eprosima::rpc::protocol::RequestHeader::operator =(
        const RequestHeader& x)
{

    m_requestId = x.m_requestId;
    m_instanceName = x.m_instanceName;

    return *this;
}

eprosima::rpc::protocol::RequestHeader& eprosima::rpc::protocol::RequestHeader::operator =(
        RequestHeader&& x)
{

    m_requestId = std::move(x.m_requestId);
    m_instanceName = std::move(x.m_instanceName);

    return *this;
}

bool eprosima::rpc::protocol::RequestHeader::operator ==(
        const RequestHeader& x) const
{

    return (m_requestId == x.m_requestId && m_instanceName == x.m_instanceName);
}

bool eprosima::rpc::protocol::RequestHeader::operator !=(
        const RequestHeader& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::RequestHeader::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::SampleIdentity_t::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::RequestHeader::getCdrSerializedSize(
        const eprosima::rpc::protocol::RequestHeader& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::SampleIdentity_t::getCdrSerializedSize(data.requestId(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.instanceName().size() + 1;


    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::RequestHeader::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_requestId;
    scdr << m_instanceName.c_str();

}

void eprosima::rpc::protocol::RequestHeader::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_requestId;
    {
        std::string aux;
        dcdr >> aux;
        m_instanceName = aux.c_str();
    }
}

/*
 * @brief This function copies the value in member requestId
 * @param _requestId New value to be copied in member requestId
 */
void eprosima::rpc::protocol::RequestHeader::requestId(
        const eprosima::rpc::protocol::SampleIdentity_t& _requestId)
{
    m_requestId = _requestId;
}

/*
 * @brief This function moves the value in member requestId
 * @param _requestId New value to be moved in member requestId
 */
void eprosima::rpc::protocol::RequestHeader::requestId(
        eprosima::rpc::protocol::SampleIdentity_t&& _requestId)
{
    m_requestId = std::move(_requestId);
}

/*
 * @brief This function returns a constant reference to member requestId
 * @return Constant reference to member requestId
 */
const eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::RequestHeader::requestId() const
{
    return m_requestId;
}

/*
 * @brief This function returns a reference to member requestId
 * @return Reference to member requestId
 */
eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::RequestHeader::requestId()
{
    return m_requestId;
}
/*
 * @brief This function copies the value in member instanceName
 * @param _instanceName New value to be copied in member instanceName
 */
void eprosima::rpc::protocol::RequestHeader::instanceName(
        const eprosima::rpc::protocol::InstanceName& _instanceName)
{
    m_instanceName = _instanceName;
}

/*
 * @brief This function moves the value in member instanceName
 * @param _instanceName New value to be moved in member instanceName
 */
void eprosima::rpc::protocol::RequestHeader::instanceName(
        eprosima::rpc::protocol::InstanceName&& _instanceName)
{
    m_instanceName = std::move(_instanceName);
}

/*
 * @brief This function returns a constant reference to member instanceName
 * @return Constant reference to member instanceName
 */
const eprosima::rpc::protocol::InstanceName& eprosima::rpc::protocol::RequestHeader::instanceName() const
{
    return m_instanceName;
}

/*
 * @brief This function returns a reference to member instanceName
 * @return Reference to member instanceName
 */
eprosima::rpc::protocol::InstanceName& eprosima::rpc::protocol::RequestHeader::instanceName()
{
    return m_instanceName;
}

size_t eprosima::rpc::protocol::RequestHeader::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool eprosima::rpc::protocol::RequestHeader::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::RequestHeader::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

eprosima::rpc::protocol::ReplyHeader::ReplyHeader()
{
    // m_relatedRequestId com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@31304f14

    // m_relatedInstanceName com.eprosima.idl.parser.typecode.AliasTypeCode@34a3d150
    m_relatedInstanceName ="";
    // m_remoteEx com.eprosima.idl.parser.typecode.EnumTypeCode@2a4fb17b
    m_remoteEx = eprosima::rpc::protocol::REMOTE_EX_OK;

}

eprosima::rpc::protocol::ReplyHeader::~ReplyHeader()
{



}

eprosima::rpc::protocol::ReplyHeader::ReplyHeader(
        const ReplyHeader& x)
{
    m_relatedRequestId = x.m_relatedRequestId;
    m_relatedInstanceName = x.m_relatedInstanceName;
    m_remoteEx = x.m_remoteEx;
}

eprosima::rpc::protocol::ReplyHeader::ReplyHeader(
        ReplyHeader&& x)
{
    m_relatedRequestId = std::move(x.m_relatedRequestId);
    m_relatedInstanceName = std::move(x.m_relatedInstanceName);
    m_remoteEx = x.m_remoteEx;
}

eprosima::rpc::protocol::ReplyHeader& eprosima::rpc::protocol::ReplyHeader::operator =(
        const ReplyHeader& x)
{

    m_relatedRequestId = x.m_relatedRequestId;
    m_relatedInstanceName = x.m_relatedInstanceName;
    m_remoteEx = x.m_remoteEx;

    return *this;
}

eprosima::rpc::protocol::ReplyHeader& eprosima::rpc::protocol::ReplyHeader::operator =(
        ReplyHeader&& x)
{

    m_relatedRequestId = std::move(x.m_relatedRequestId);
    m_relatedInstanceName = std::move(x.m_relatedInstanceName);
    m_remoteEx = x.m_remoteEx;

    return *this;
}

bool eprosima::rpc::protocol::ReplyHeader::operator ==(
        const ReplyHeader& x) const
{

    return (m_relatedRequestId == x.m_relatedRequestId && m_relatedInstanceName == x.m_relatedInstanceName && m_remoteEx == x.m_remoteEx);
}

bool eprosima::rpc::protocol::ReplyHeader::operator !=(
        const ReplyHeader& x) const
{
    return !(*this == x);
}

size_t eprosima::rpc::protocol::ReplyHeader::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::SampleIdentity_t::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t eprosima::rpc::protocol::ReplyHeader::getCdrSerializedSize(
        const eprosima::rpc::protocol::ReplyHeader& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += eprosima::rpc::protocol::SampleIdentity_t::getCdrSerializedSize(data.relatedRequestId(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.relatedInstanceName().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void eprosima::rpc::protocol::ReplyHeader::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_relatedRequestId;
    scdr << m_relatedInstanceName.c_str();
    scdr << (uint32_t)m_remoteEx;

}

void eprosima::rpc::protocol::ReplyHeader::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_relatedRequestId;
    {
        std::string aux;
        dcdr >> aux;
        m_relatedInstanceName = aux.c_str();
    }
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_remoteEx = (eprosima::rpc::protocol::RemoteExceptionCode_t)enum_value;
    }

}

/*
 * @brief This function copies the value in member relatedRequestId
 * @param _relatedRequestId New value to be copied in member relatedRequestId
 */
void eprosima::rpc::protocol::ReplyHeader::relatedRequestId(
        const eprosima::rpc::protocol::SampleIdentity_t& _relatedRequestId)
{
    m_relatedRequestId = _relatedRequestId;
}

/*
 * @brief This function moves the value in member relatedRequestId
 * @param _relatedRequestId New value to be moved in member relatedRequestId
 */
void eprosima::rpc::protocol::ReplyHeader::relatedRequestId(
        eprosima::rpc::protocol::SampleIdentity_t&& _relatedRequestId)
{
    m_relatedRequestId = std::move(_relatedRequestId);
}

/*
 * @brief This function returns a constant reference to member relatedRequestId
 * @return Constant reference to member relatedRequestId
 */
const eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::ReplyHeader::relatedRequestId() const
{
    return m_relatedRequestId;
}

/*
 * @brief This function returns a reference to member relatedRequestId
 * @return Reference to member relatedRequestId
 */
eprosima::rpc::protocol::SampleIdentity_t& eprosima::rpc::protocol::ReplyHeader::relatedRequestId()
{
    return m_relatedRequestId;
}
/*
 * @brief This function copies the value in member relatedInstanceName
 * @param _relatedInstanceName New value to be copied in member relatedInstanceName
 */
void eprosima::rpc::protocol::ReplyHeader::relatedInstanceName(
        const eprosima::rpc::protocol::InstanceName& _relatedInstanceName)
{
    m_relatedInstanceName = _relatedInstanceName;
}

/*
 * @brief This function moves the value in member relatedInstanceName
 * @param _relatedInstanceName New value to be moved in member relatedInstanceName
 */
void eprosima::rpc::protocol::ReplyHeader::relatedInstanceName(
        eprosima::rpc::protocol::InstanceName&& _relatedInstanceName)
{
    m_relatedInstanceName = std::move(_relatedInstanceName);
}

/*
 * @brief This function returns a constant reference to member relatedInstanceName
 * @return Constant reference to member relatedInstanceName
 */
const eprosima::rpc::protocol::InstanceName& eprosima::rpc::protocol::ReplyHeader::relatedInstanceName() const
{
    return m_relatedInstanceName;
}

/*
 * @brief This function returns a reference to member relatedInstanceName
 * @return Reference to member relatedInstanceName
 */
eprosima::rpc::protocol::InstanceName& eprosima::rpc::protocol::ReplyHeader::relatedInstanceName()
{
    return m_relatedInstanceName;
}
/*
 * @brief This function sets a value in member remoteEx
 * @param _remoteEx New value for member remoteEx
 */
void eprosima::rpc::protocol::ReplyHeader::remoteEx(
        eprosima::rpc::protocol::RemoteExceptionCode_t _remoteEx)
{
    m_remoteEx = _remoteEx;
}

/*
 * @brief This function returns the value of member remoteEx
 * @return Value of member remoteEx
 */
eprosima::rpc::protocol::RemoteExceptionCode_t eprosima::rpc::protocol::ReplyHeader::remoteEx() const
{
    return m_remoteEx;
}

/*
 * @brief This function returns a reference to member remoteEx
 * @return Reference to member remoteEx
 */
eprosima::rpc::protocol::RemoteExceptionCode_t& eprosima::rpc::protocol::ReplyHeader::remoteEx()
{
    return m_remoteEx;
}


size_t eprosima::rpc::protocol::ReplyHeader::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool eprosima::rpc::protocol::ReplyHeader::isKeyDefined()
{
    return false;
}

void eprosima::rpc::protocol::ReplyHeader::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}



